version: '3.8'

services:
  bridge:
    image: sagenet_backend-bridge:latest
    container_name: energy_bridge
    command: python app/main_bridge.py
    restart: always
    env_file: .env
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
      - ./logs:/app/logs
    networks:
      - web_network

  api:
    image: sagenet_backend-api:latest
    container_name: energy_api
    command: uvicorn app.main_api:app --host 0.0.0.0 --port 8000
    restart: always
    # --- CRITICAL CHANGE ---
    ports:
      - "127.0.0.1:8000:8000" # Maps Container Port 8000 -> Host Port 8000
    # -----------------------
    env_file: .env
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
      - ./logs:/app/logs
    networks:
      - web_network

networks:
  web_network:
    external: true