version: '3.8'

services:
  bridge:
    image: sagenet_backend-bridge:latest
    container_name: energy_bridge
    command: python app/main_bridge.py
    restart: always
    # --- FIX: USE HOST NETWORK DIRECTLY ---
    network_mode: "host"
    # --------------------------------------
    env_file: .env
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
      - ./logs:/app/logs

  api:
    image: sagenet_backend-api:latest
    container_name: energy_api
    # This command opens Port 8000 directly on the server
    command: uvicorn app.main_api:app --host 0.0.0.0 --port 8000
    restart: always
    # --- FIX: USE HOST NETWORK DIRECTLY ---
    network_mode: "host"
    # --------------------------------------
    env_file: .env
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
      - ./logs:/app/logs